### ISSUE TITLE
Issues when using the output from write_colony 

### ISSUE THREAD

**Issue by laurabenestan** [thierrygosselin/radiator#110]
Dear Thierry,

I want to create a colony file from a vcf.
I then used your nice function write_colony with the following command lines:
vcf <- tidy_vcf("18512snps-276ind-diplodus.vcf")
write_colony(vcf)

Then, when I am trying to run Colony, I get the following error message:

Opening & reading data input file: radiator_colony_20210112@1441

Marker 16616 has the same ID, scaffold10026_cov197, as marker 16617

Errors in DATA. Insufficient data or incorrect format.
Please check DATA and format and then re-run the program
Program stopped in subroutine StopOnDataError, dataset = radiator_colony_20210112@1441.

Yet, my marker IDs are all unique, then the scaffold10026_cov197 is also unique. 
I have noticed that in the colony example dataset marker IDs are separated by 5 interspaces while in the file that radiator produce, only I observe one interspace between each marker names.
As I have 276 individuals genotyped at 18,516SNPs I do not think the error is related to the size of the dataset.

Any idea how I can deal with this error? 

Best regards,

Laura

**Comment by thierrygosselin** [comment]
Hey Laura, there is still some [edits to do on the colony file generated](https://thierrygosselin.github.io/radiator/reference/write_colony.html#details), but the format between the markers names is probably not the problem because this function as received little change for the last 6 years and as worked well. It could be the markers names... if there's a lot of weird characters, colony might not like that...

For me to reproduce, verify and potential fix the problem with radiator, I'll need:

- the vcf file
- the colony file you generated
- radiator version you're using
- colony version you're using
- the OS you're running colony on ... PC, macOS, Linux ?

If colony bug with certain character, I could modify `radiator::write_colony` to detect those and change it.

Best,
Thierry

**Comment by laurabenestan** [comment]
Hi Thierry,

Thank you for your response.
In fact, COLONY does not like loci names that exceed 20 letters.
So I just changed the loci names to unique numbers and I modified lines 307 and 308 which were missing two values (one in each line). I have now indicated to these lines :

 
0  0                ! Number of offspring with known father, exclusion threshold
0  0                ! Number of offspring with known mother, exclusion threshold

It works and thank you very much for providing an easy way to turn a genepop into a colony file in R.
Have a nice day,

Laura

**Comment by thierrygosselin** [comment]
yes, for some datasets, depending on options you select, you'll need to tweak the file generated by radiator, that is just a skeleton to work with.

[write_colony doc details](https://thierrygosselin.github.io/radiator/reference/write_colony.html#details
)

**Comment by thierrygosselin** [comment]
You also can use the argument `print.all.colony.opt` and change the default to `print.all.colony.opt = TRUE`
[doc](https://thierrygosselin.github.io/radiator/reference/write_colony.html)
