### ISSUE TITLE
question about converting genind to VCF with genomic_converter

### ISSUE THREAD

**Issue by leonvarhan** [thierrygosselin/radiator#148]
Hello,
I'm getting a warning message when running genomic_converter to create a .vcf file from a genind object. Could you please help me interpret this messsage and if it is creating an issue with my VCF file?  The input gening object has  7,726 loci and the resulting .vcf file from genomic_converter shows: Number of markers: 1520

**Warning message:**
Problem with `mutate()` column `LOCUS`.
`LOCUS = stringi::stri_join(LOCUS, as.numeric(POS) - 1, sep = "_")`.
NAs introduced by coercion 

**I am running R version 3.6.3. The code is:**
genomic_converter(infile_poly_25_miss, strata = "strata.txt", 
                  output = "vcf", vcf.metadata = TRUE, vcf.stats = TRUE, filename ="infile_poly_25_miss", verbose = TRUE)

Thank you so much for your time!
Leo

**Comment by thierrygosselin** [comment]
Hi Leo, I'll need a little more than that. Please follow guidelines below and written when you reported the issue. Otherwise, it's impossible for me check why it's not working on your end.

**guidelines**
I cannot help you if I cannot reproduce the problem.
Consequently, when reporting an issue, make sure to include:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Include the steps to reproduce the behavior:
* the exact command (function, arguments, values) used
* the complete error message you're getting
* the output of `devtools::session_info()`
* complete data required to reproduce the problem, a subset of it. The data remains confidential.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by thierrygosselin** [comment]
Re-open the issue if necessary
