### ISSUE TITLE
error using genomic_converter genlight to genepop

### ISSUE THREAD

**Issue by pidita** [thierrygosselin/radiator#149]
Hello,
I am trying to convert a genlight object (created using SambaR) to a genepop file, but I get an error. Below the script I am using and the error that I get.

Thanks in advance.

> genomic_converter(mygenlight, output="genepop", filename="EM_gp")
################################################################################
################################################################################
Execution date@time: 20211231@1321
Folder created: 01_radiator_genomic_converter_20211231@1321
Function call and arguments stored in: radiator_genomic_converter_args_20211231@1321.tsv
Filters parameters file generated: filters_parameters_20211231@1321.tsv

Importing data: genlight
Calibrating REF/ALT alleles...
Calibrating REF/ALT alleles...

Writing tidy data set:
EM_gp.rad

Preparing data for output

Data is bi-allelic
Calibrating REF/ALT alleles...
Error: Problem with `mutate()` column `GT`.
i `GT = stringi::stri_join(A1, A1)`.
x objeto 'A1' no encontrado
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 3 sec

**Comment by thierrygosselin** [comment]
Hi 

I cannot help you if I cannot reproduce the problem.
Consequently, when reporting an issue, make sure to include:

**Describe the bug**

- [ ] A clear and concise description of what the bug is

**To Reproduce**
Include the steps to reproduce the behavior:

- [ ] the exact command (function, arguments, values) used
- [ ] the complete error message you're getting
- [ ] the output of `devtools::session_info()`
- [ ] complete data required to reproduce the problem, a subset of it. The data remains confidential.

**Screenshots**
- [ ] If applicable, add screenshots to help explain your problem.

**Comment by thierrygosselin** [comment]
you might want to try adegenet for this in the meantime...

**Comment by pidita** [comment]
Hi,

Thanks for your response. I finally managed to create a genpop object using SambaR.
