### ISSUE TITLE
filter_dart

### ISSUE THREAD

**Issue by tunaloveheart** [thierrygosselin/radiator#15]
Hey 

Getting this error on file that has previously worked fine with filter_dart

Next step requires the genotypes
Importing DArT data
Error in overscope_eval_next(overscope, expr) : 
  object 'TARGET_ID' not found

Thanks

**Comment by thierrygosselin** [comment]
Could you try again with latest release and tell me if you're still getting the problem. 
If you do, send me the data, so that I can reproduce the problem and fix it

Best

**Comment by tunaloveheart** [comment]
Hey 

Yeah I tried with the latest realises I pulled from you GIT and thats when I started having troubles. Ive attached a DArT file I have worked with previously and had no problems with. Your a life saver. 

Kind Regards
Dani

**Comment by thierrygosselin** [comment]
Hi Dani,
Can you send me the DArT file + strata file and command you used so that I can reproduce the problem.
Best

**Comment by thierrygosselin** [comment]
Make sure that you read the new doc...
`TARGET_ID` error suggest that you don't have this column in the strata file.
This is the unique id given by DArT.
Not sure ? Use the function `extract_dart_target_id`
This will help you to create the strata file.

**strata file:**
A tab delimited file with 3 columns. Columns header is:
`TARGET_ID`, `INDIVIDUALS` and `STRATA`.
Note: the column`STRATA` refers to any grouping of individuals.
You need to make sure that
the column `TARGET_ID` match the id used by DArT.
The column `INDIVIDUALS` and `STRATA` will be kept in the tidy data.
**Only individuals in the strata file are kept in the tidy, i.e. that the strata
is also used as a whitelist of individuals/strata.**


It's probably this that changed since you last used `filter_dart`.

**Why these changes?**
To accommodate more DArT files that were presented to me and make sure that the tidying process is made correctly.

Please re-open the issue if this doesn't fix your problem

**Comment by tunaloveheart** [comment]
Thanks :)

**Comment by tunaloveheart** [comment]
Hey Thierry
Please ignore my last email!! Hope your enjoying your time in the
wilderness.

:) Dani
-- 

[image: --]

Danielle Davenport
[image: http://]about.me/ddavenport
<http://about.me/ddavenport?promo=email_sig>
