### ISSUE TITLE
allele order changes when using genomic_converter

### ISSUE THREAD

**Issue by BrennaF** [thierrygosselin/radiator#20]
Hi Thierry - sorry to bug you again, but I'm having an issue with genomic_converter renaming my alleles from those of my input file.

For example, I have a simulation data set in genind format that shows counts of my alleles "100" and "110":

```
> miss.genind@tab[1:5,1:10]
    0.100 0.110 1.100 1.110 10.100 10.110 11.100 11.110 12.100 12.110
001     2     0     1     1      1      1      0      2      2      0
002     0     2     1     1      0      2      1      1      0      2
003     2     0     0     2      2      0      2      0      2      0
004     0     2     1     1     NA     NA      0      2      1      1
005     1     1     0     2      0      2      1      1     NA     NA
```
I run genomic_converter like so:
```
foo <- genomic_converter(data=miss.genind, output="genind", imputation.method="rf", hierarchical.levels="global", verbose = TRUE)
```
When I look at the output data, the alleles are renamed A1/A2 -- but not consistently. For example, A1 does not always = allele "100" from the original dataset.

```
> foo$genind.imputed@tab[1:5,1:10]
    0.A1 0.A2 1.A1 1.A2 10.A1 10.A2 11.A1 11.A2 12.A1 12.A2
001    0    2    1    1     1     1     2     0     2     0
002    2    0    1    1     2     0     1     1     0     2
003    0    2    0    2     0     2     0     2     2     0
004    2    0    1    1    NA    NA     2     0     1     1
005    1    1    0    2     2     0     1     1    NA    NA
```
Individual 3 is a good example if you compare across the data sets.

That's a problem for me since I am taking only one column per locus from the imputed data frame for downstream analysis (for example, I need all of the "110" allele counts).

Can you tweak genomic_converter so it doesn't rename the alleles? That would probably be easiest (?)

Hope that makes sense - I can send the data set if needed.
Thanks so much! (And no huge hurry!)
Brenna

**Comment by thierrygosselin** [comment]
Hi Brenna,

Should be working now with latest commit.
There's now a new argument in `tidy_genind` called `keep.allele.names` it's logical `TRUE/FALSE` that allows to keep naming. There's one condition, it requires all the alleles to be numeric. 
There's a cost, for huge dataset, it will be a bit longer, because i'm using user-supplied value and not `A1` and `A2`. The cost is similar to multi-allelic dataset or biallelic tidy dataset that didn't have `GT_BIN` as column.

The argument is passed silently in `...` dots-dots-dots for functions: `tidy_genomic_data` and 
`genomic_converter`. So use the argument at the end of all other arguments.

The default is: `keep.allele.names = FALSE` so that it works with actual codes.

Reason in the first place for `A1` and `A2` with bi-allelic dataset ? I've seen so many way to mess genotypes, id, pop, markers and locus names that I kept it simple for bi-allelic dataset where `A1` and `A2` was for REF and ALT allele.

Cheers
Thierry

**Comment by BrennaF** [comment]
Fantastic, thanks Thierry! I'll give it a shot in the next few days. The A1/A2 naming comes out of the landscape genetics simulation program CDPOP.
