### ISSUE TITLE
Is there a way to not trim for markers in common when using the write_pcadapt function in radiator

### ISSUE THREAD

**Issue by Ella-Bowles** [thierrygosselin/radiator#29]
Hi Thierry,

Is there a way to not trim for markers in common when using the write_pcadapt function in radiator? I don't see a field for this in the documentation, but I'd like to try PCAdapt using all of the markers in my tidy file.

With thanks,
Ella

**Comment by thierrygosselin** [comment]
Why would you want that to run an outlier test ?

**Comment by thierrygosselin** [comment]
You might have been mislead by pcadapt, it is great with missing data because of it's use of the Mahalanobis distance, but there's no shortcut for low coverage RADseq dataset. If you're using pcadapt to look for positive/directional selection between populations, you need common markers.

Note that if it's the brook charr dataset you sent before, because of it's overall low QC and low coverage (markers and individuals)... the missing markers, the ones not in common between populations/sampling sites, are not biological... it's more probable that it's artifactual.

But hey we live in a free world of ideas, if you still want to do it, download the .R file called write_pcadapt and comment (#) line 98. 

save and source that file (don't use radiator::write_pcadapt) in your code.
