### ISSUE TITLE
Loading VCF issue

### ISSUE THREAD

**Issue by DiedeMaas90** [thierrygosselin/radiator#56]
Hi,

I'm trying to generate some basic stats for my STACKS generated haplotype data (nucleotide diversity per individual, number polymorphic/monomorphic loci per sampling site). I have a populations.haps.vcf file and I generated a tsv file with my individuals and strata.

In my understanding I first need to generate a tidy file. However, when I use either tidy_vcf() or tidy_genomic_data() I receive the following error:

**tidy.data <- tidy_vcf(data = "populations.haps.vcf", strata = "popmap_2019_LinA.tsv")

Reading VCF
Data summary: 
    number of samples: 308
    number of markers: 7163
done! timing: 1 sec

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 43 / 43
Generating individual stats...
Error: Argument 2 must be length 2192960, not 0**

What am I missing here?

Best, Diede

**Comment by thierrygosselin** [comment]
Hi Diede,

This is not normal behavior. Something is wrong in your VCF or strata file.

Do you mind sending the strata file: `popmap_2019_LinA.tsv` so that I can have a look. The VCF as well (a subset of the first few 100 lines is good enough). 

If sending by email is a problem:

1. check that you have followed the instruction to [generate the strata file](https://thierrygosselin.github.io/radiator/reference/read_strata.html) (coming from stacks, it's really easy.

2. make sure the names are the same between the vcd and strata


Best
Thierry

**Comment by DiedeMaas90** [comment]
Hi Thierry,

Sure, I've attached the tsv file and the first 300 lines of the vcf file!

Diede

**Comment by thierrygosselin** [comment]
thierrygosselin@icloud.com

**Comment by DiedeMaas90** [comment]
Hi Thierry,

Whoops, sorry something went wrong with my previous comment. Anyway. I have attached a zip file with the tsv file and the first 300 lines of my vcf file.

[DiedeMaas90.zip](https://github.com/thierrygosselin/radiator/files/3501925/DiedeMaas90.zip)


Cheers, Diede

**Comment by thierrygosselin** [comment]
I thought the problem was fixed...
The issue, is that stacks sometimes says that the VCF contains certain info in the format field, here in the haplotype VCF:
```
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allele Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
```

When in fact stacks just output the GT field...This is problematic for SeqArray (the VCF import engine behind radiator).

The quick fix, while I push a new version, is to keep only the GT field in the VCF header:

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
```
You delete those lines:
```
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allele Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
```
This is easily done in text editor, etc.

**Comment by thierrygosselin** [comment]
I've pushed a new commit, it should work. Re-open the issue if you're still having problem.
Thanks for reporting.
Thierry
